version: '3.8'
services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - 8090:8080
    volumes:
      - jenkins-vol:/var/jenkins_home
    deploy:
      resources:
        limits:
          memory: 3072M
        reservations:
          memory: 1024M
volumes:
  jenkins-vol:
